out: "C:/Users/bzlis/Videos/Path of Exile/3.23/accuracy_stack_jugg/assets/"
nodes:
  - Oath of the Maji
  - Claws of the Hawk
  - Claws of the Falcon
  - Life Raker
  - Wildwood Blessing
  - Lesson of the Seasons
items:
  - The Untouched Soul
  - Replica Last Resort
  - Unset Ring
  - Split Personality:
      - +40 to Accuracy Rating
      - +5 to Intelligence
skills:
  - Petrified Blood
  - Lightning Strike
  - Lightning Strike of Arcing
